### ISSUE TITLE
We need some automated testing around our sass compilation

### ISSUE THREAD

**Issue by AlexOverbeck** [mobi/gosheets#5]
It would be really nice if we could get some baseline automated testing at least just to ensure that out main sass file can compile successfully. 

If we had a linter it would help us avoid some of this, but I think we would all feel better if we knew that what we were writing doesn't bring down anyone else's software.

I've done a bit of research. we might be able to integrate some really basic sass compilation into [Travis CI](https://travis-ci.org/) or some similar tool.

Something like this would even be enough for now, though, I would maybe want to see if we could get this done with node rather than ruby. https://mattandre.ws/2014/01/testing-sass-travis-ci/

**Comment by StevenUlmer** [comment]
https://github.com/mobi/gosheets/pull/26

**Comment by AlexOverbeck** [comment]
Closed out again in #28
